TxnManager.Web/Controllers/UploadTransactionFileController.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TxnManager.Domain.Service.Abstractions;
using TxnManager.Web.Dto;

namespace TxnManager.Controllers
{
    public class UploadTransactionFileController : Controller
    {
        private readonly IUploadService _uploadService;

        public UploadTransactionFileController(IUploadService uploadService)
        {
            _uploadService = uploadService;
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Upload(UploadDocumentDto doc)
        {
            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }

            using (var stream = doc.FormFile.OpenReadStream())
            {
                await _uploadService.UploadTransactionsFileAsync(stream, doc.GetExtension(),
                    CancellationToken.None);
            }

            // we could return Ok() here
            // but I return View() to be able to upload new files.
            return View();
        }
    }
}

TxnManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Txn Manager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="UploadTransactionFile" asp-action="Upload">Txn Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Txn Manager
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TxnManager.Web/Views/UploadTransactionFile/Upload.cshtml
<form id="uploadForm" asp-action="Upload" asp-controller="UploadTransactionFile" method="post" enctype="multipart/form-data">
    <input type="file" name="doc.FormFile" /><br>
    <input id="process" type="submit" value="Upload" />
</form>

<div id="loading" class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
</div>

<div asp-validation-summary="All"></div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $("#loading").hide();

            $('#process').click(function() {
                $('#uploadForm').submit();
            });

            $("#uploadForm").submit(function() {
                $("#loading").show();
            });
        });
    </script>
}